# Welcome to Jekyll!
#

# Site settings
title: astralship
description: We are solutionares and changemakers converting chapel in the North Wales into an environtment to realise human potential and heal the planet.ğŸŒ&nbsp;&nbsp;ğŸŒ&nbsp;&nbsp;ğŸŒ
owner: Your Name # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: email@genesis.re
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://astralship.org" # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/theastralship
  github: https://github.com/AstralDynamics
  linkedin-square: https://www.linkedin.com/company/astral-dynamics-cyf
  facebook-official: https://www.facebook.com/AstralDynamicsCyf
  #ngoogle-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
